### ISSUE TITLE
missing rom for previous devices

### ISSUE THREAD

**Issue by dpeddi** [SiliconLabs/video_si21xx_superset#1]
Good morning, 

It seems that in this repository are missing following files
 "Si2164_ROM1_Patch16_4_0b31.h"
 "Si2167_ROM0_Patch16_2_5b0.h"    
 "Si2167B_ROM0_Patch_2_2b10.h"

Regards

**Comment by MarcDorval** [comment]
Hi,

I uploaded the missing files. Thanks for the heads up!

**Comment by dpeddi** [comment]
thank you, issue seems closed
