### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by dpeddi** [SiliconLabs/video_si21xx_superset#2]
I'm building this superset with

-DNO_WIN32 -DLINUX_KERNEL_DRIVER

the build fails with
```
 error: implicit declaration of function 'realloc' [-Werror=implicit-function-declara
     front_end->demod->fw_table = (firmware_struct*)realloc(front_end->demod->fw_table , sizeof(firmware_struct)*front_end->demod->nbLines);

```
around line 3131 of Si2183_L2_API.c you write to comment out some portions but probably that comment can be replaced or integrated with  an ifndef LINUX_KERNEL_DRIVER

Regards

**Comment by MarcDorval** [comment]
The driver is not expected to directly compile on all platforms without adaptations.
To facilitate locating the areas where porting work may be required, we use the <porting> marker, so look out for <porting> all over the code and you'll find out these locations.
Surrounding these lines with ifndef LINUX_KERNEL_DRIVER will only be valid if ALL linux platforms forbid using dynamic allocation.
By the way, these are only useful if you don't want to embed the FW files as `.h` files (which most people do), and prefer to have them as files in your filesystem, which you will then need to 'load' using `SiLabs_API_Store_FW()`.
If you don't need this feature, just comment the lines.
PS.: nearly nobody uses SPI download as well, so the SPI-related line can be commented out on most applications.

**Comment by dpeddi** [comment]
ok, thank you for clarification
